### ISSUE TITLE
A few issues on a clean install

### ISSUE THREAD

**Issue by Syonyk** [BernardoGiordano/signal-desktop-pi4#1]
Trying this on my Ubuntu 20.04 PineBook Pro, I found a few issues in the script:

* libcrypto++8 doesn't exist, it's libcrypto++6 - not a big deal, easy change, though the script could detect releases.

* After installing nvm, if it's not been installed before, the proper script needs to be run so that nvm is available to a bash script.
```
 curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
 
+export NVM_DIR=$HOME/.nvm;
+source $NVM_DIR/nvm.sh;
+
 echo "installing nvm 14.16.0..."
```

* Inconsistency between nvm install and nvm use.
```
 nvm install 14.16.0
-nvm use 14.6.0
+nvm use 14.16.0
 
 echo "installing rustup..."
```

Same "source after install" for rustup.
```
echo "installing rustup..."
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
+ source $HOME/.cargo/env
```

Unfortunately, it then seems to try to use a nightly rustc build and fails.

```
compiling libzkgroup...
RUSTFLAGS='-C link-arg=-s' cargo build --release
info: syncing channel updates for 'nightly-2021-09-19-aarch64-unknown-linux-gnu'
info: latest update on 2021-09-19, rust version 1.57.0-nightly (aa8f2d432 2021-09-18)
info: downloading component 'cargo'

...

   Compiling proc-macro2 v1.0.27
   Compiling unicode-xid v0.2.2
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: "Provided allocation has wrong size for slot count 131072"', compiler/rustc_metadata/src/rmeta/decoder.rs:263:29
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: "Provided allocation has wrong size for slot count 131072"', compiler/rustc_metadata/src/rmeta/decoder.rs:263:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
note: the compiler unexpectedly panicked. this is a bug.


```

**Comment by junefish** [comment]
> maybe `$rustup override set 1.51.0`

The script was failing for me on line 51 and this fixed it, thanks!

**Comment by BernardoGiordano** [comment]
It also works if you run the commands line by line rather than in the script. Anyways a fix has been pushed and I'll check if the script is now fixed in the next few days

**Comment by junefish** [comment]
I was actually running the commands line-by-line.  After I ran line 51 I got errors.  After I ran the rustup override command, I re-ran line 51 and it completed with no errors.
